import type { Metadata } from "next";
import Link from "next/link";
import { redirect } from "next/navigation";
import { createServerSupabaseClient } from "@/lib/supabase/server";
import { routes } from "@/config/routes";
import { getProfilePhotoUrl } from "@/lib/profile-photo";
import { ProfileFormLoader } from "./profile-form-loader";
import { ArrowLeft, CheckCircle2, ShieldCheck, Sparkles } from "lucide-react";

export const metadata: Metadata={title:"Dating Profile | Extrovert"}; export const dynamic="force-dynamic";
export default async function ProfileSetupPage(){
 const supabase=await createServerSupabaseClient(); const {data:claimsData}=await supabase.auth.getClaims(); const userId=typeof claimsData?.claims?.sub==="string"?claimsData.claims.sub:null; if(!userId)redirect(routes.login);
 const [{data:interests},{data:existingProfile},{data:existingPhotos},{data:existingPi},{data:existingPreferences},{data:identity}]=await Promise.all([
  supabase.from("interests").select("id,name").order("name"),supabase.from("profiles").select("bio,campus_residency,campus_hangout,relationship_goal,zodiac,sleep_habit,caffeine_pref,weekend_vibe,prompt_question,prompt_answer").eq("id",userId).maybeSingle(),supabase.from("profile_photos").select("storage_path,display_order,is_primary").eq("profile_id",userId).order("display_order"),supabase.from("profile_interests").select("interest_id").eq("profile_id",userId),supabase.from("dating_preferences").select("interested_in,min_age,max_age,preferred_department").eq("user_id",userId).maybeSingle(),supabase.from("extrovert_profiles").select("display_name,date_of_birth,gender,department,academic_year,identity_type,institution_name,field_of_study,job_title,employer_name,role_description,area_id,profile_completed,trust_state,verification_status,area_verification_status").eq("id",userId).maybeSingle()
 ]);
 if(!identity)redirect(`${routes.login}?error=extrovert_identity_required`);
 const paths=(existingPhotos??[]).map(p=>p.storage_path); const urls=paths.flatMap(p=>{const u=getProfilePhotoUrl(p,320);return u?[u]:[]}); const interestIds=(existingPi??[]).map(r=>r.interest_id);
 const {data:area}=identity.area_id?await supabase.from("extrovert_areas").select("name").eq("id",identity.area_id).maybeSingle():{data:null};
 const context=identity.identity_type==="student"?`${identity.institution_name||"College / university"} · ${identity.department||"Student"}${identity.academic_year?` · ${identity.academic_year}`:""}`:identity.identity_type==="professional"?`${identity.job_title||"Professional"}${identity.employer_name?` · ${identity.employer_name}`:""}`:(identity.role_description||"Current role");
 const complete=Boolean(identity.profile_completed);
 return <main className="mx-auto w-full max-w-3xl px-3.5 pb-28 pt-5 font-sans sm:px-5">
  <header className="mb-5 flex items-start justify-between gap-4"><div><Link href={routes.profile} className="mb-3 inline-flex items-center gap-1 text-[10px] font-bold text-zinc-500 hover:text-emerald-700"><ArrowLeft className="h-3.5 w-3.5"/>Profile</Link><p className="text-[10px] font-black uppercase tracking-[.18em] text-emerald-600">EXTROVERT DATE</p><h1 className="mt-1 text-3xl font-black tracking-tight">Make your profile feel like you.</h1><p className="mt-2 max-w-2xl text-xs leading-5 text-zinc-500">Build the version people meet in Discover. Identity details are updated here in one place; the choices below shape your dating presence.</p></div><div className="hidden shrink-0 items-center gap-2 rounded-full border border-emerald-100 bg-emerald-50 px-3 py-2 text-[9px] font-black text-emerald-700 sm:flex"><ShieldCheck className="h-3.5 w-3.5"/>Privacy-first</div></header>
  <section className="mb-5 grid gap-3 rounded-[1.75rem] border border-emerald-100 bg-emerald-50/60 p-4 shadow-sm sm:grid-cols-[1fr_auto]"><div><div className="flex items-center gap-2"><div className="grid h-9 w-9 place-items-center rounded-xl bg-white text-emerald-600 shadow-sm"><Sparkles className="h-4 w-4"/></div><div><p className="text-[9px] font-black uppercase tracking-wider text-emerald-700">Shared Extrovert identity</p><p className="text-sm font-black text-emerald-950">{identity.display_name||"Extrovert member"}</p></div></div><p className="mt-3 text-[10px] leading-4 text-emerald-900/75">{context} · {area?.name||"Area not set"}</p></div><div className="flex items-center gap-2 self-start rounded-2xl border border-white bg-white px-3 py-2 text-[9px] font-bold text-zinc-600"><CheckCircle2 className={`h-3.5 w-3.5 ${complete?"text-emerald-600":"text-zinc-300"}`}/>{complete?"Profile live":"Setup in progress"}</div></section>
  <ProfileFormLoader userId={userId} interests={interests??[]} existingProfile={existingProfile} existingPhotoUrls={urls} existingPhotoPaths={paths} existingInterestIds={interestIds} existingPreferences={existingPreferences} identity={{displayName:identity.display_name??"",dateOfBirth:identity.date_of_birth??"",gender:identity.gender??"",department:identity.department,academicYear:identity.academic_year,identityType:identity.identity_type??"student",institutionName:identity.institution_name,fieldOfStudy:identity.field_of_study,jobTitle:identity.job_title,employerName:identity.employer_name,roleDescription:identity.role_description,areaName:area?.name??"",verificationStatus:identity.verification_status}}/>
 </main>;
}
