"use client";
import dynamic from "next/dynamic";
import { Loader2, ShieldCheck, GraduationCap, Briefcase, MapPin, UserRound, CalendarDays } from "lucide-react";
import type { ReactNode } from "react";
import { calculateAge } from "@/lib/utils";

interface Interest{id:string;name:string}
interface ExistingProfile{bio:string|null;campus_residency?:string|null;campus_hangout?:string|null;relationship_goal?:string|null;zodiac?:string|null;sleep_habit?:string|null;caffeine_pref?:string|null;weekend_vibe?:string|null;prompt_question?:string|null;prompt_answer?:string|null}
interface ExistingPreferences{interested_in:string[]|null;min_age:number|null;max_age:number|null;preferred_department:string|null}
interface Identity{displayName:string;dateOfBirth:string;gender:string;department:string|null;academicYear:string|null;identityType:string;institutionName:string|null;fieldOfStudy:string|null;jobTitle:string|null;employerName:string|null;roleDescription:string|null;areaName?:string}
interface Props{userId:string;interests:Interest[];existingProfile:ExistingProfile|null;existingPhotoUrls:string[];existingPhotoPaths:string[];existingInterestIds:string[];existingPreferences:ExistingPreferences|null;identity:Identity}

const LazyDatingProfileForm=dynamic(()=>import("./dating-profile-form").then(m=>m.DatingProfileForm),{ssr:false,loading:()=> <div className="flex min-h-40 items-center justify-center rounded-3xl border border-zinc-200 bg-white"><Loader2 className="h-5 w-5 animate-spin text-emerald-600" aria-label="Loading profile editor"/></div>});
function clean(value:string|null|undefined){return value?.trim()||"Not added"}
function prettyType(value:string){const v=value.trim().toLowerCase();return v==="student"?"Student":v==="professional"?"Professional":v==="other"?"Other":value?value.replace(/[-_]+/g," ").replace(/\b\w/g,c=>c.toUpperCase()):"Not set"}
function prettyGender(value:string){const v=value.trim().toLowerCase();if(v==="man")return"Man";if(v==="woman")return"Woman";if(v==="non-binary"||v==="nonbinary")return"Non-binary";return value?value.replace(/[-_]+/g," ").replace(/\b\w/g,c=>c.toUpperCase()):"Not set"}
function prettyYear(value:string|null){if(!value)return"Not added";const map:Record<string,string>={"1st-year":"1st year","2nd-year":"2nd year","3rd-year":"3rd year","4th-year":"4th year","5th-year":"5th year",postgraduate:"Postgraduate"};return map[value]??value.replace(/[-_]+/g," ").replace(/\b\w/g,c=>c.toUpperCase())}
function Info({icon,label,value}:{icon:ReactNode;label:string;value:string}){return <div className="rounded-2xl border border-zinc-200 bg-zinc-50/70 p-3"><div className="flex items-center gap-1.5 text-[9px] font-black uppercase tracking-wider text-zinc-500">{icon}{label}</div><p className="mt-1.5 break-words text-xs font-black text-zinc-900">{value}</p></div>}
function IdentityContextCards({identity}:{identity:Identity}){const type=identity.identityType.trim().toLowerCase();const isStudent=type==="student";const isProfessional=type==="professional";const age=identity.dateOfBirth?calculateAge(identity.dateOfBirth):null;const contextTitle=isStudent?"Student context":isProfessional?"Work context":"Current context";return <>
<section className="rounded-3xl border border-zinc-200 bg-white p-4 shadow-sm sm:p-5"><div className="mb-4 flex items-start gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-2xl bg-emerald-50 text-emerald-700"><ShieldCheck className="h-5 w-5"/></div><div><h2 className="text-base font-black text-zinc-950">Who are you?</h2><p className="mt-1 text-[10px] leading-4 text-zinc-500">Your verified Extrovert identity, shown clearly and consistently across your profile.</p></div></div><div className="grid grid-cols-2 gap-2.5 sm:grid-cols-4"><Info icon={<UserRound className="h-3 w-3"/>} label="Name" value={clean(identity.displayName)}/><Info icon={<ShieldCheck className="h-3 w-3"/>} label="Gender" value={prettyGender(identity.gender)}/><Info icon={<CalendarDays className="h-3 w-3"/>} label="Age" value={age!==null?String(age):"Not available"}/><Info icon={<MapPin className="h-3 w-3"/>} label="Area" value={clean(identity.areaName)}/></div><div className="mt-3 flex flex-wrap items-center gap-2"><span className="rounded-full bg-emerald-50 px-3 py-1.5 text-[10px] font-black text-emerald-800">{prettyType(identity.identityType)}</span><span className="rounded-full bg-zinc-100 px-3 py-1.5 text-[10px] font-bold text-zinc-600">Identity details are managed by Extrovert</span></div></section>
<section className="rounded-3xl border border-zinc-200 bg-white p-4 shadow-sm sm:p-5"><div className="mb-4 flex items-start gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-2xl bg-emerald-50 text-emerald-700">{isStudent?<GraduationCap className="h-5 w-5"/>:<Briefcase className="h-5 w-5"/>}</div><div><h2 className="text-base font-black text-zinc-950">{contextTitle}</h2><p className="mt-1 text-[10px] leading-4 text-zinc-500">The study or work details people see on your dating profile.</p></div></div>{isStudent?<div className="grid grid-cols-2 gap-2.5"><Info icon={<GraduationCap className="h-3 w-3"/>} label="College / university" value={clean(identity.institutionName)}/><Info icon={<Briefcase className="h-3 w-3"/>} label="Course / department" value={clean(identity.department)}/><Info icon={<GraduationCap className="h-3 w-3"/>} label="Field of study" value={clean(identity.fieldOfStudy)}/><Info icon={<CalendarDays className="h-3 w-3"/>} label="Academic year" value={prettyYear(identity.academicYear)}/></div>:isProfessional?<div className="grid grid-cols-2 gap-2.5"><Info icon={<Briefcase className="h-3 w-3"/>} label="Job / role" value={clean(identity.jobTitle)}/><Info icon={<Briefcase className="h-3 w-3"/>} label="Company / organisation" value={clean(identity.employerName)}/><div className="col-span-2"><Info icon={<UserRound className="h-3 w-3"/>} label="About the role" value={clean(identity.roleDescription)}/></div></div>:<Info icon={<UserRound className="h-3 w-3"/>} label="What you do" value={clean(identity.roleDescription)}/>}</section></>}
export function ProfileFormLoader(props:Props){return <div className="profile-editor space-y-4"><IdentityContextCards identity={props.identity}/><div className="[&>form>div:has(.lucide-shield-check)]:hidden [&>form>div:has(.lucide-graduation-cap)]:hidden [&>form>div:has(.lucide-briefcase)]:hidden"><LazyDatingProfileForm {...props}/></div></div>}
