"use client";

import {useCallback,useEffect,useMemo,useState} from "react";
import {CalendarDays,Clock3,MapPin,Plus,Users,X,Crown,MessageCircle,Check,ChevronRight,Send,UserCheck,UserX,LogOut} from "lucide-react";
import {Button} from "@/components/ui/button";
import {createClient} from "@/lib/supabase/client";

type DbPlan={id:string;coordinator_id:string;title:string;emoji:string;category:string;area_name:string;starts_at:string;max_members:number;description:string;status:string};
type Plan={id:string;coordinatorId:string;emoji:string;title:string;area:string;startsAt:string;members:number;capacity:number;coordinator:string;description:string;category:string;isMember:boolean;isCoordinator:boolean};
type Request={id:string;plan_id:string;requester_id:string;status:string;name:string};
type ChatMessage={id:string;plan_id:string;sender_id:string;content:string;created_at:string;sender:string};

const categories=["All","Chill","Food","Movies","Adventure","Travel","Music"];
const categoryValue=(v:string)=>v.toLowerCase();
const formatWhen=(value:string)=>{const d=new Date(value);return {date:d.toLocaleDateString("en-IN",{weekday:"short",day:"numeric",month:"short"}),time:d.toLocaleTimeString("en-IN",{hour:"numeric",minute:"2-digit"})};};

export default function ExplorePlans(){
 const supabase=useMemo(()=>createClient(),[]);
 const [userId,setUserId]=useState(""); const [plans,setPlans]=useState<Plan[]>([]); const [requests,setRequests]=useState<Request[]>([]);
 const [category,setCategory]=useState("All"); const [selected,setSelected]=useState<Plan|null>(null); const [creating,setCreating]=useState(false); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false);
 const [chat,setChat]=useState<ChatMessage[]>([]); const [message,setMessage]=useState(""); const [chatLoading,setChatLoading]=useState(false); const [showRequests,setShowRequests]=useState(false);

 const loadPlans=useCallback(async(uid:string)=>{
   const {data,error}=await supabase.from("explore_plans").select("id,coordinator_id,title,emoji,category,area_name,starts_at,max_members,description,status").neq("status","cancelled").order("starts_at",{ascending:true}).limit(60);
   if(error){console.error(error);setLoading(false);return;}
   const raw=(data??[]) as DbPlan[]; const ids=raw.map(p=>p.id);
   const {data:members}=ids.length?await supabase.from("explore_plan_members").select("plan_id,user_id,role").in("plan_id",ids):{data:[]};
   const memberRows=(members??[]) as {plan_id:string;user_id:string;role:string}[];
   const peopleIds=[...new Set([...raw.map(p=>p.coordinator_id),...memberRows.map(m=>m.user_id)])];
   const {data:profiles}=peopleIds.length?await supabase.from("extrovert_profiles").select("id,display_name").in("id",peopleIds):{data:[]};
   const names=new Map((profiles??[]).map((p:{id:string;display_name:string})=>[p.id,p.display_name||"Member"]));
   setPlans(raw.map(p=>{const ms=memberRows.filter(m=>m.plan_id===p.id);return {id:p.id,coordinatorId:p.coordinator_id,emoji:p.emoji,title:p.title,area:p.area_name,startsAt:p.starts_at,members:ms.length,capacity:p.max_members,coordinator:names.get(p.coordinator_id)||"Member",description:p.description,category:p.category,isMember:ms.some(m=>m.user_id===uid),isCoordinator:p.coordinator_id===uid};}));
   if(selected){const next=raw.find(p=>p.id===selected.id);if(!next)setSelected(null);}
   setLoading(false);
 },[supabase,selected]);

 const loadRequests=useCallback(async(uid:string)=>{
   const ownPlanIds=plans.filter(p=>p.isCoordinator).map(p=>p.id); if(!ownPlanIds.length){setRequests([]);return;}
   const {data}=await supabase.from("explore_plan_join_requests").select("id,plan_id,requester_id,status").in("plan_id",ownPlanIds).eq("status","pending").order("created_at",{ascending:true});
   const rows=(data??[]) as Omit<Request,"name">[]; const ids=rows.map(r=>r.requester_id); const {data:profiles}=ids.length?await supabase.from("extrovert_profiles").select("id,display_name").in("id",ids):{data:[]}; const names=new Map((profiles??[]).map((p:{id:string;display_name:string})=>[p.id,p.display_name||"Member"]));
   setRequests(rows.map(r=>({...r,name:names.get(r.requester_id)||"Member"})));
 },[supabase,plans]);

 useEffect(()=>{let active=true;(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!active||!user)return;setUserId(user.id);await loadPlans(user.id);})();return()=>{active=false;};},[supabase,loadPlans]);
 useEffect(()=>{if(userId)loadRequests(userId);},[userId,loadRequests]);

 const refresh=()=>userId&&loadPlans(userId);
 const visible=category==="All"?plans:plans.filter(p=>p.category===categoryValue(category));

 async function createPlan(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);const date=String(f.get("date"));const time=String(f.get("time"));const startsAt=new Date(`${date}T${time}`).toISOString();const {data,error}=await supabase.rpc("create_explore_plan",{p_title:String(f.get("title")),p_emoji:String(f.get("emoji")||"✨"),p_category:categoryValue(String(f.get("category")||"Chill")),p_area_name:String(f.get("area")),p_starts_at:startsAt,p_max_members:Math.max(2,Math.min(20,Number(f.get("capacity"))||6)),p_description:String(f.get("description")||"")});setBusy(false);if(error){alert(error.message);return;}setCreating(false);await refresh();if(data){const made=plans.find(p=>p.id===(data as DbPlan).id);if(made)setSelected(made);}}

 async function requestJoin(plan:Plan){setBusy(true);const {error}=await supabase.rpc("request_to_join_explore_plan",{p_plan_id:plan.id});setBusy(false);if(error){alert(error.message);return;}setPlans(v=>v.map(p=>p.id===plan.id?{...p}:p));await refresh();}
 async function decide(req:Request,accept:boolean){setBusy(true);const {error}=await supabase.rpc("decide_explore_plan_request",{p_request_id:req.id,p_accept:accept});setBusy(false);if(error){alert(error.message);return;}await refresh();}
 async function leave(plan:Plan){setBusy(true);const {error}=await supabase.rpc("leave_explore_plan",{p_plan_id:plan.id});setBusy(false);if(error){alert(error.message);return;}await refresh();setSelected(null);}
 async function removeMember(plan:Plan,user:string){setBusy(true);const {error}=await supabase.rpc("remove_explore_plan_member",{p_plan_id:plan.id,p_user_id:user});setBusy(false);if(error){alert(error.message);return;}await refresh();}
 async function cancelPlan(plan:Plan){setBusy(true);const {error}=await supabase.rpc("cancel_explore_plan",{p_plan_id:plan.id});setBusy(false);if(error){alert(error.message);return;}await refresh();setSelected(null);}

 const openChat=async(plan:Plan)=>{setSelected(plan);setChatLoading(true);const {data}=await supabase.from("explore_plan_messages").select("id,plan_id,sender_id,content,created_at").eq("plan_id",plan.id).order("created_at",{ascending:true}).limit(100);const ids=[...new Set((data??[]).map((m:{sender_id:string})=>m.sender_id))];const {data:profiles}=ids.length?await supabase.from("extrovert_profiles").select("id,display_name").in("id",ids):{data:[]};const names=new Map((profiles??[]).map((p:{id:string;display_name:string})=>[p.id,p.display_name||"Member"]));setChat((data??[]).map((m:{id:string;plan_id:string;sender_id:string;content:string;created_at:string})=>({...m,sender:names.get(m.sender_id)||"Member"})));setChatLoading(false);setShowRequests(false);};
 useEffect(()=>{if(!selected||!selected.isMember)return;const channel=supabase.channel(`explore-plan:${selected.id}`).on("postgres_changes",{event:"INSERT",schema:"public",table:"explore_plan_messages",filter:`plan_id=eq.${selected.id}`},async(payload)=>{const m=payload.new as {id:string;plan_id:string;sender_id:string;content:string;created_at:string};if(chat.some(x=>x.id===m.id))return;const {data:p}=await supabase.from("extrovert_profiles").select("display_name").eq("id",m.sender_id).maybeSingle();setChat(v=>[...v,{...m,sender:p?.display_name||"Member"}]);}).on("postgres_changes",{event:"*",schema:"public",table:"explore_plan_members",filter:`plan_id=eq.${selected.id}`},()=>{refresh();}).on("postgres_changes",{event:"*",schema:"public",table:"explore_plan_join_requests",filter:`plan_id=eq.${selected.id}`},()=>{refresh();loadRequests(userId);}).subscribe();return()=>{supabase.removeChannel(channel);};},[selected,supabase,userId,loadRequests,refresh]);
 async function sendMessage(e:React.FormEvent){e.preventDefault();const text=message.trim();if(!text||!selected||!selected.isMember)return;setMessage("");const {error}=await supabase.from("explore_plan_messages").insert({plan_id:selected.id,sender_id:userId,content:text});if(error)alert(error.message);}

 return <main className="mx-auto w-full max-w-5xl px-3 pb-24 pt-4 font-sans sm:px-5">
  <header className="flex items-end justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-emerald-600">Explore</p><h1 className="mt-1 text-3xl font-black tracking-tight">Find something to do.</h1><p className="mt-1 max-w-lg text-xs text-zinc-500">Real plans. Real people. One shared lobby.</p></div><div className="flex gap-2"><Button size="md" variant="outline" onClick={()=>setShowRequests(true)} leftIcon={<UserCheck className="h-4 w-4"/>}>Requests{requests.length>0&&<span className="ml-1 rounded-full bg-emerald-600 px-1.5 text-[8px] text-white">{requests.length}</span>}</Button><Button size="md" leftIcon={<Plus className="h-4 w-4"/>} onClick={()=>setCreating(true)}>Create Plan</Button></div></header>
  <div className="mt-5 flex gap-2 overflow-x-auto pb-1">{categories.map(c=><button key={c} type="button" onClick={()=>setCategory(c)} className={`shrink-0 rounded-full border px-3.5 py-2 text-[10px] font-black transition ${category===c?"border-emerald-600 bg-emerald-600 text-white":"border-zinc-200 bg-white text-zinc-600 hover:border-emerald-200"}`}>{c}</button>)}</div>
  <section className="mt-6"><div className="mb-3 flex items-center justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.18em] text-emerald-600">Live lobbies</p><h2 className="text-lg font-black">Plans near you</h2></div><span className="rounded-full bg-zinc-100 px-2.5 py-1 text-[9px] font-black text-zinc-500">{loading?"Loading…":`${visible.length} plans`}</span></div>
   {visible.length===0&&!loading?<div className="rounded-[1.8rem] border border-dashed border-zinc-200 bg-zinc-50 p-10 text-center"><div className="text-3xl">🗺️</div><h3 className="mt-2 text-sm font-black">No plans yet</h3><p className="mt-1 text-xs text-zinc-500">Create the first lobby and let people request to join.</p></div>:<div className="grid gap-3 sm:grid-cols-2">{visible.map(plan=>{const w=formatWhen(plan.startsAt);return <button key={plan.id} type="button" onClick={()=>setSelected(plan)} className="group rounded-[1.7rem] border border-zinc-200 bg-white p-4 text-left shadow-sm transition hover:-translate-y-0.5 hover:border-emerald-200 hover:shadow-md"><div className="flex items-start gap-3"><div className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-zinc-50 text-2xl">{plan.emoji}</div><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><h3 className="truncate text-base font-black">{plan.title}</h3><span className="rounded-full bg-emerald-50 px-2 py-1 text-[8px] font-black text-emerald-700">{plan.status?.toUpperCase()||"OPEN"}</span></div><p className="mt-1 line-clamp-2 text-[11px] leading-4 text-zinc-500">{plan.description}</p></div></div><div className="mt-4 grid grid-cols-2 gap-2 text-[9px] font-bold text-zinc-500"><span><MapPin className="mr-1 inline h-3 w-3 text-emerald-600"/>{plan.area}</span><span><Clock3 className="mr-1 inline h-3 w-3 text-emerald-600"/>{w.date} · {w.time}</span></div><div className="mt-4 flex items-center justify-between border-t border-zinc-100 pt-3"><span className="text-[9px] font-black text-zinc-500"><Users className="mr-1 inline h-3.5 w-3.5 text-emerald-600"/>{plan.members}/{plan.capacity} players · {plan.coordinator}</span><ChevronRight className="h-4 w-4 text-zinc-300 transition group-hover:translate-x-0.5 group-hover:text-emerald-600"/></div></button>})}</div>}
  </section>

  {selected&&<div className="fixed inset-0 z-[100] grid place-items-center bg-zinc-950/25 p-3 sm:p-5" onClick={()=>setSelected(null)}><div className="w-full max-w-xl max-h-[92vh] overflow-y-auto rounded-[2rem] border border-white/70 bg-white p-5 shadow-2xl" onClick={e=>e.stopPropagation()}><div className="flex items-start gap-3"><div className="grid h-14 w-14 shrink-0 place-items-center rounded-2xl bg-zinc-50 text-3xl">{selected.emoji}</div><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><div><p className="text-[9px] font-black uppercase tracking-[.18em] text-emerald-600">Plan lobby</p><h2 className="mt-1 text-xl font-black">{selected.title}</h2></div><button type="button" onClick={()=>setSelected(null)} className="grid h-9 w-9 place-items-center rounded-full bg-zinc-100"><X className="h-4 w-4"/></button></div><p className="mt-1 text-[10px] text-zinc-500">👑 {selected.coordinator} · Coordinator</p></div></div>
   <div className="mt-5 grid grid-cols-2 gap-2"><div className="rounded-2xl bg-zinc-50 p-3"><MapPin className="h-4 w-4 text-emerald-600"/><p className="mt-1 text-[9px] font-black text-zinc-400">MEET AT</p><p className="text-xs font-black">{selected.area}</p></div><div className="rounded-2xl bg-zinc-50 p-3"><CalendarDays className="h-4 w-4 text-emerald-600"/><p className="mt-1 text-[9px] font-black text-zinc-400">WHEN</p><p className="text-xs font-black">{formatWhen(selected.startsAt).date}</p><p className="text-[9px] font-bold text-zinc-500">{formatWhen(selected.startsAt).time}</p></div></div>
   <div className="mt-4 rounded-2xl border border-zinc-200 p-3"><div className="flex items-center justify-between"><span className="text-[9px] font-black uppercase tracking-wider text-zinc-400">Players</span><span className="text-xs font-black">{selected.members}/{selected.capacity}</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-zinc-100"><div className="h-full rounded-full bg-emerald-500 transition-all" style={{width:`${Math.min(100,selected.members/selected.capacity*100)}%`}}/></div></div>
   <p className="mt-3 text-xs leading-5 text-zinc-500">{selected.description}</p>
   {selected.isMember&&<div className="mt-4 rounded-2xl border border-zinc-200 p-3"><div className="flex items-center justify-between"><h3 className="text-xs font-black">Lobby chat</h3><span className="text-[8px] font-bold text-emerald-600">LIVE</span></div><div className="mt-3 max-h-44 space-y-2 overflow-y-auto rounded-xl bg-zinc-50 p-2">{chatLoading?<p className="p-3 text-center text-[10px] text-zinc-400">Loading chat…</p>:chat.length===0?<p className="p-3 text-center text-[10px] text-zinc-400">No messages yet. Start the plan.</p>:chat.map(m=><div key={m.id} className={`rounded-xl px-3 py-2 text-[10px] ${m.sender_id===userId?"ml-8 bg-emerald-600 text-white":"mr-8 bg-white text-zinc-700"}`}><div className="mb-0.5 text-[8px] font-black opacity-60">{m.sender}</div>{m.content}</div>)}</div><form onSubmit={sendMessage} className="mt-2 flex gap-2"><input value={message} onChange={e=>setMessage(e.target.value)} maxLength={1000} placeholder="Message the lobby…" className="h-10 min-w-0 flex-1 rounded-xl border border-zinc-200 px-3 text-xs"/><Button type="submit" size="sm" disabled={!message.trim()} leftIcon={<Send className="h-3.5 w-3.5"/>}>Send</Button></form></div>}
   <div className="mt-4 flex flex-wrap gap-2">{!selected.isMember&&!selected.isCoordinator&&<Button className="flex-1" disabled={busy||selected.members>=selected.capacity} onClick={()=>requestJoin(selected)} leftIcon={<Users className="h-4 w-4"/>}>{selected.members>=selected.capacity?"Lobby full":"Request to join"}</Button>}{selected.isMember&&!selected.isCoordinator&&<Button variant="outline" className="flex-1" disabled={busy} onClick={()=>leave(selected)} leftIcon={<LogOut className="h-4 w-4"/>}>Leave lobby</Button>}{selected.isCoordinator&&<Button variant="outline" className="flex-1" disabled={busy} onClick={()=>cancelPlan(selected)} leftIcon={<X className="h-4 w-4"/>}>Cancel plan</Button>}</div>
   {selected.isCoordinator&&<div className="mt-4 rounded-2xl border border-emerald-100 bg-emerald-50/60 p-3"><div className="flex items-center justify-between"><h3 className="text-xs font-black">Join requests</h3><span className="text-[9px] font-black text-emerald-700">{requests.filter(r=>r.plan_id===selected.id).length} pending</span></div>{requests.filter(r=>r.plan_id===selected.id).map(r=><div key={r.id} className="mt-2 flex items-center justify-between rounded-xl bg-white p-2"><span className="text-[10px] font-black">{r.name}</span><div className="flex gap-1"><button type="button" onClick={()=>decide(r,true)} disabled={busy} className="grid h-8 w-8 place-items-center rounded-lg bg-emerald-600 text-white"><Check className="h-3.5 w-3.5"/></button><button type="button" onClick={()=>decide(r,false)} disabled={busy} className="grid h-8 w-8 place-items-center rounded-lg bg-zinc-100"><UserX className="h-3.5 w-3.5"/></button></div></div>)}</div>}
  </div></div>}

  {creating&&<div className="fixed inset-0 z-[101] grid place-items-center bg-zinc-950/25 p-3 sm:p-5" onClick={()=>setCreating(false)}><form onSubmit={createPlan} onClick={e=>e.stopPropagation()} className="w-full max-w-lg max-h-[92vh] overflow-y-auto rounded-[2rem] bg-white p-5 shadow-2xl"><div className="flex items-center justify-between"><div><p className="text-[9px] font-black uppercase tracking-[.18em] text-emerald-600">Create lobby</p><h2 className="mt-1 text-xl font-black">Create a Plan</h2></div><button type="button" onClick={()=>setCreating(false)} className="grid h-9 w-9 place-items-center rounded-full bg-zinc-100"><X className="h-4 w-4"/></button></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="sm:col-span-2 text-[10px] font-black">Plan name<input name="title" required placeholder="Coffee after class" className="mt-1 h-11 w-full rounded-2xl border border-zinc-200 px-3 text-xs font-medium"/></label><label className="text-[10px] font-black">Emoji<input name="emoji" defaultValue="☕" maxLength={2} className="mt-1 h-11 w-full rounded-2xl border border-zinc-200 px-3 text-lg"/></label><label className="text-[10px] font-black">Category<select name="category" className="mt-1 h-11 w-full rounded-2xl border border-zinc-200 px-3 text-xs"><option>Chill</option><option>Food</option><option>Movies</option><option>Adventure</option><option>Travel</option><option>Music</option></select></label><label className="text-[10px] font-black">Area<input name="area" required placeholder="Shimla" className="mt-1 h-11 w-full rounded-2xl border border-zinc-200 px-3 text-xs"/></label><label className="text-[10px] font-black">Date<input name="date" type="date" required className="mt-1 h-11 w-full rounded-2xl border border-zinc-200 px-3 text-xs"/></label><label className="text-[10px] font-black">Time<input name="time" type="time" required className="mt-1 h-11 w-full rounded-2xl border border-zinc-200 px-3 text-xs"/></label><label className="text-[10px] font-black">Player limit<input name="capacity" type="number" min={2} max={20} defaultValue={6} className="mt-1 h-11 w-full rounded-2xl border border-zinc-200 px-3 text-xs"/></label><label className="sm:col-span-2 text-[10px] font-black">Description<textarea name="description" rows={3} maxLength={500} placeholder="What are you planning?" className="mt-1 w-full resize-none rounded-2xl border border-zinc-200 p-3 text-xs"/></label></div><div className="mt-4 flex gap-2"><Button type="button" variant="outline" className="flex-1" onClick={()=>setCreating(false)}>Cancel</Button><Button type="submit" disabled={busy} className="flex-1" leftIcon={<Plus className="h-4 w-4"/>}>{busy?"Creating…":"Open Lobby"}</Button></div></form></div>}

  {showRequests&&<div className="fixed inset-0 z-[102] grid place-items-center bg-zinc-950/25 p-3 sm:p-5" onClick={()=>setShowRequests(false)}><div className="w-full max-w-lg rounded-[2rem] bg-white p-5 shadow-2xl" onClick={e=>e.stopPropagation()}><div className="flex items-center justify-between"><div><p className="text-[9px] font-black uppercase tracking-[.18em] text-emerald-600">Coordinator</p><h2 className="text-xl font-black">Join requests</h2></div><button type="button" onClick={()=>setShowRequests(false)} className="grid h-9 w-9 place-items-center rounded-full bg-zinc-100"><X className="h-4 w-4"/></button></div>{requests.length===0?<p className="py-10 text-center text-xs text-zinc-500">No pending requests.</p>:<div className="mt-4 space-y-2">{requests.map(r=><div key={r.id} className="rounded-2xl border border-zinc-100 p-3"><div className="flex items-center justify-between"><div><p className="text-xs font-black">{r.name}</p><p className="text-[9px] text-zinc-400">Join request</p></div><div className="flex gap-1"><button type="button" onClick={()=>decide(r,true)} disabled={busy} className="grid h-9 w-9 place-items-center rounded-xl bg-emerald-600 text-white"><Check className="h-4 w-4"/></button><button type="button" onClick={()=>decide(r,false)} disabled={busy} className="grid h-9 w-9 place-items-center rounded-xl bg-zinc-100"><UserX className="h-4 w-4"/></button></div></div></div>)}</div>}</div></div>}
 </main>;
}
