import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft, Bell, Calendar, Megaphone, MessageSquareHeart, Newspaper, Sparkles, Wrench } from "lucide-react";
import { createServerSupabaseClient } from "@/lib/supabase/server";
import { routes } from "@/config/routes";
import { FeedbackForm } from "./feedback-form";

export const metadata: Metadata = { title: "News & Announcements" };
export const dynamic = "force-dynamic";
const labels: Record<string, string> = { announcement: "Announcement", update: "Product update", maintenance: "Maintenance" };

export default async function NewsPage() {
  const supabase = await createServerSupabaseClient();
  const { data: posts, error } = await supabase.from("news_posts").select("id,title,body,post_type,created_at").eq("is_published", true).order("created_at", { ascending: false }).limit(20);
  return <main className="mx-auto min-h-[calc(100dvh-4rem)] w-full max-w-md overflow-y-auto bg-white px-3.5 py-4 font-sans select-none pb-28"><div className="flex items-center gap-3 px-1"><Link href={routes.discover} className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full border border-zinc-200 bg-white text-zinc-500 shadow-xs transition-all hover:text-zinc-900 active:scale-95" aria-label="Back to discover"><ArrowLeft className="h-4 w-4" /></Link><div><div className="inline-flex items-center gap-1.5 rounded-full border border-emerald-200 bg-emerald-50 px-2 py-0.5 text-[10px] font-bold text-emerald-700"><Bell className="h-3 w-3" /> Updates</div><h1 className="text-xl font-black tracking-tight text-zinc-950">News &amp; Announcements</h1></div></div>
  <section className="mt-4 space-y-3">{error?<div className="rounded-3xl border border-rose-200 bg-rose-50/70 p-5 text-center"><p className="text-xs font-bold text-rose-700">Updates couldn&apos;t load</p><p className="mt-1 text-[10px] text-rose-600">Please try again in a moment.</p></div>:(posts??[]).length===0?<div className="rounded-3xl border border-dashed border-zinc-200 bg-zinc-50 p-6 text-center"><div className="mx-auto flex h-10 w-10 items-center justify-center rounded-2xl bg-white text-emerald-600 shadow-xs"><Sparkles className="h-5 w-5"/></div><p className="mt-2 text-xs font-bold text-zinc-900">No announcements yet</p><p className="mt-1 text-[11px] text-zinc-500">Check back when something new ships.</p></div>:(posts??[]).map(post=>{const Icon=post.post_type==="maintenance"?Wrench:post.post_type==="update"?Newspaper:Megaphone;return <article key={post.id} className="rounded-3xl border border-zinc-200 bg-white p-4 shadow-xs"><div className="flex items-center justify-between gap-2"><span className="inline-flex items-center gap-1.5 rounded-full border border-emerald-200 bg-emerald-50 px-2.5 py-1 text-[9px] font-black text-emerald-700"><Icon className="h-3 w-3"/>{labels[post.post_type]??"Update"}</span><span className="flex items-center gap-1 text-[9px] font-semibold text-zinc-400"><Calendar className="h-3 w-3"/><time dateTime={post.created_at}>{new Date(post.created_at).toLocaleDateString("en-IN",{day:"numeric",month:"short",year:"numeric"})}</time></span></div><h2 className="mt-3 text-sm font-black leading-snug text-zinc-950">{post.title}</h2><p className="mt-1.5 whitespace-pre-wrap text-xs leading-5 text-zinc-600">{post.body}</p></article>})}</section>
  <section className="mt-4 rounded-3xl border border-zinc-200 bg-zinc-50 p-4 shadow-xs"><div className="flex items-start gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-2xl bg-white text-emerald-600 shadow-xs"><MessageSquareHeart className="h-5 w-5"/></div><div className="min-w-0 flex-1"><p className="text-[10px] font-black uppercase tracking-[0.16em] text-emerald-700">Help shape Extrovert</p><h2 className="mt-0.5 text-sm font-black text-zinc-950">Send feedback</h2><p className="mt-1 text-[11px] leading-5 text-zinc-500">Bug, idea or something confusing? Keep it short and specific so we can act on it.</p></div></div><FeedbackForm/></section>
  <section className="mt-3 rounded-3xl border border-emerald-200 bg-emerald-50/60 p-4"><div className="flex items-center gap-2 text-xs font-black text-emerald-900"><Bell className="h-4 w-4"/> Follow updates</div><p className="mt-1 text-[10px] leading-4 text-emerald-800">Turn on notifications for important matches, messages, plans, and Extrovert updates.</p></section>
  </main>;
}
