"use client";

import { useEffect, useState } from "react";
import { Bell, X } from "lucide-react";

function base64UrlToUint8Array(value:string){const padding="=".repeat((4-(value.length%4))%4);const raw=window.atob((value+padding).replace(/-/g,"+").replace(/_/g,"/"));return Uint8Array.from(raw,(char)=>char.charCodeAt(0));}
async function registerServiceWorker(){if(!("serviceWorker"in navigator))return null;try{return await navigator.serviceWorker.register("/sw.js",{scope:"/"});}catch{return null;}}
async function syncPushSubscription(){const registration=await registerServiceWorker();if(!registration||!("PushManager"in window)||!("Notification"in window)||Notification.permission!=="granted")return false;try{const existing=await registration.pushManager.getSubscription();if(existing){const saved=await fetch("/api/push/subscribe",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(existing.toJSON())});return saved.ok;}const keyResponse=await fetch("/api/push/vapid-public-key",{cache:"no-store"});if(!keyResponse.ok)return false;const {publicKey}=await keyResponse.json();if(typeof publicKey!=="string"||!publicKey)return false;const subscription=await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:base64UrlToUint8Array(publicKey)});const saved=await fetch("/api/push/subscribe",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(subscription.toJSON())});return saved.ok;}catch{return false;}}

export function PushNotifications(){const [ready,setReady]=useState(false);const [permission,setPermission]=useState<NotificationPermission|"unsupported">("unsupported");const [showPrompt,setShowPrompt]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);
 useEffect(()=>{let cancelled=false;let timer:number|undefined;const setup=async()=>{const supported=typeof window!=="undefined"&&window.isSecureContext&&"serviceWorker"in navigator&&"PushManager"in window&&"Notification"in window;if(!supported){setPermission("unsupported");return;}timer=window.setTimeout(async()=>{await registerServiceWorker();if(cancelled)return;setReady(true);const current=Notification.permission;setPermission(current);if(current==="granted"){void syncPushSubscription();return;}if(current==="default"&&sessionStorage.getItem("extrovert_notification_prompt_dismissed")!=="1")setShowPrompt(true);},1500);};void setup();return()=>{cancelled=true;if(timer)window.clearTimeout(timer);};},[]);
 if(!ready||permission==="unsupported"||!showPrompt)return null;
 const dismiss=()=>{sessionStorage.setItem("extrovert_notification_prompt_dismissed","1");setShowPrompt(false);};
 const enable=async()=>{setBusy(true);setError(null);try{const next=await Notification.requestPermission();setPermission(next);if(next!=="granted"){if(next==="denied")setError("Notifications are blocked in this browser.");return;}const ok=await syncPushSubscription();if(!ok){setError("Notifications are not available on this device yet.");return;}dismiss();}finally{setBusy(false);}};
 return <div className="fixed inset-x-3 bottom-[calc(5rem+env(safe-area-inset-bottom))] z-[100000] mx-auto max-w-sm"><div className="rounded-3xl border border-emerald-100 bg-white p-4 shadow-xl"><div className="flex items-start gap-3"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-2xl bg-emerald-50 text-emerald-600"><Bell className="h-5 w-5"/></div><div className="min-w-0 flex-1"><p className="text-sm font-black text-zinc-950">Stay in the loop</p><p className="mt-1 text-[11px] leading-4 text-zinc-600">Get alerts for likes, matches and messages.</p>{error&&<p className="mt-1 text-[10px] font-semibold text-amber-700">{error}</p>}</div><button type="button" onClick={dismiss} aria-label="Not now" className="rounded-full p-1.5 text-zinc-400"><X className="h-4 w-4"/></button></div><div className="mt-3 flex gap-2"><button type="button" onClick={()=>void enable()} disabled={busy} className="flex flex-1 items-center justify-center gap-2 rounded-2xl bg-emerald-600 px-4 py-3 text-xs font-black text-white disabled:opacity-60">{busy?"Enabling…":"Enable notifications"}</button><button type="button" onClick={dismiss} className="rounded-2xl border border-zinc-200 px-4 py-3 text-xs font-bold text-zinc-600">Not now</button></div></div></div>;
}
