import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft, Bell, Eye, FileText, Megaphone, Trash2, Wrench } from "lucide-react";
import { requireAdminRole } from "@/lib/auth/admin";
import { createAdminClient } from "@/lib/supabase/admin";
import { routes } from "@/config/routes";
import { createNewsPost, deleteNewsPost, updateNewsPost } from "./actions";

export const metadata: Metadata = { title: "Announcements | DateLocal Admin", robots: { index: false, follow: false } };
export const dynamic = "force-dynamic";

const typeLabel: Record<string, string> = { announcement: "Announcement", update: "Product update", maintenance: "Maintenance" };
const typeIcon: Record<string, typeof Megaphone> = { announcement: Megaphone, update: FileText, maintenance: Wrench };

export default async function AdminNewsPage() {
  await requireAdminRole("ADMIN");
  const db = createAdminClient();
  const { data: posts } = await db.from("news_posts").select("id,title,body,post_type,is_published,created_by,created_at,updated_at").order("created_at", { ascending: false }).limit(50);

  return <main className="min-h-screen bg-zinc-50 font-sans text-zinc-950"><header className="sticky top-0 z-30 border-b border-zinc-200 bg-white/95 backdrop-blur"><div className="mx-auto flex h-14 max-w-5xl items-center justify-between px-4 sm:px-6"><div className="flex items-center gap-3"><Link href={routes.admin.root} className="grid h-8 w-8 place-items-center rounded-lg border border-zinc-200 text-zinc-500 hover:bg-zinc-50" aria-label="Back to admin"><ArrowLeft className="h-4 w-4"/></Link><div><p className="text-[9px] font-black uppercase tracking-[.16em] text-emerald-600">DateLocal · Admin</p><h1 className="text-sm font-black">News & Announcements</h1></div></div><Link href={routes.news} className="inline-flex items-center gap-1.5 rounded-xl border border-zinc-200 px-3 py-2 text-[10px] font-bold text-zinc-700"><Eye className="h-3.5 w-3.5"/> View public page</Link></div></header>
  <div className="mx-auto max-w-5xl space-y-5 px-4 py-6 sm:px-6"><section className="rounded-3xl border border-emerald-200 bg-white p-5 shadow-xs"><div className="flex items-start gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-2xl bg-emerald-50 text-emerald-700"><Megaphone className="h-5 w-5"/></div><div><h2 className="text-lg font-black">Publish an update</h2><p className="mt-1 text-[10px] leading-5 text-zinc-500">Posts appear in the user-facing News & Announcements page. Keep updates useful, short and clear.</p></div></div><form action={createNewsPost} className="mt-5 grid gap-3"><div className="grid gap-3 sm:grid-cols-[1fr_180px]"><input name="title" required minLength={3} maxLength={120} placeholder="Title" className="rounded-xl border border-zinc-200 bg-white px-3 py-3 text-xs font-semibold outline-none focus:border-emerald-500"/><select name="postType" defaultValue="announcement" className="rounded-xl border border-zinc-200 bg-white px-3 py-3 text-xs font-semibold outline-none focus:border-emerald-500"><option value="announcement">Announcement</option><option value="update">Product update</option><option value="maintenance">Maintenance</option></select></div><textarea name="body" required minLength={3} maxLength={5000} rows={5} placeholder="What should users know?" className="resize-y rounded-xl border border-zinc-200 bg-white px-3 py-3 text-xs leading-5 outline-none focus:border-emerald-500"/><div className="flex flex-wrap items-center justify-between gap-2"><label className="inline-flex items-center gap-2 text-[10px] font-bold text-zinc-600"><input type="checkbox" name="isPublished" value="true" defaultChecked className="accent-emerald-600"/> Publish immediately</label><button className="inline-flex items-center gap-2 rounded-xl bg-emerald-600 px-4 py-3 text-xs font-black text-white shadow-sm active:scale-[.98]"><Bell className="h-3.5 w-3.5"/> Create post</button></div></form></section>
  <section className="space-y-3">{(posts??[]).map((post)=><article key={post.id} className="rounded-3xl border border-zinc-200 bg-white p-4 shadow-xs"><form action={updateNewsPost} className="space-y-3"><input type="hidden" name="id" value={post.id}/><div className="flex flex-wrap items-center justify-between gap-2"><div className="flex items-center gap-2">{(() => { const Icon=typeIcon[post.post_type]??Megaphone; return <span className="grid h-8 w-8 place-items-center rounded-xl bg-emerald-50 text-emerald-700"><Icon className="h-4 w-4"/></span>; })()}<div><p className="text-[9px] font-black uppercase tracking-wider text-zinc-400">{typeLabel[post.post_type]??post.post_type}</p><p className="text-[9px] text-zinc-400">{new Date(post.created_at).toLocaleString("en-IN")}</p></div></div><span className={`rounded-full px-2.5 py-1 text-[9px] font-black ${post.is_published?"bg-emerald-50 text-emerald-700":"bg-zinc-100 text-zinc-500"}`}>{post.is_published?"Published":"Draft"}</span></div><div className="grid gap-2 sm:grid-cols-[1fr_180px]"><input name="title" defaultValue={post.title} required maxLength={120} className="rounded-xl border border-zinc-200 px-3 py-2.5 text-xs font-black outline-none focus:border-emerald-500"/><select name="postType" defaultValue={post.post_type} className="rounded-xl border border-zinc-200 px-3 py-2.5 text-xs font-semibold outline-none focus:border-emerald-500"><option value="announcement">Announcement</option><option value="update">Product update</option><option value="maintenance">Maintenance</option></select></div><textarea name="body" defaultValue={post.body} required maxLength={5000} rows={4} className="w-full resize-y rounded-xl border border-zinc-200 px-3 py-2.5 text-xs leading-5 outline-none focus:border-emerald-500"/><div className="flex flex-wrap items-center justify-between gap-2"><label className="inline-flex items-center gap-2 text-[10px] font-bold text-zinc-600"><input type="checkbox" name="isPublished" value="true" defaultChecked={post.is_published} className="accent-emerald-600"/> Visible to users</label><div className="flex gap-2"><button className="rounded-xl bg-zinc-950 px-3.5 py-2.5 text-[10px] font-black text-white">Save</button></div></div></form><form action={deleteNewsPost} className="mt-2 flex justify-end"><input type="hidden" name="id" value={post.id}/><button className="inline-flex items-center gap-1.5 rounded-xl border border-rose-200 bg-rose-50 px-3 py-2 text-[9px] font-bold text-rose-700"><Trash2 className="h-3 w-3"/> Remove post</button></form></article>)}{(posts??[]).length===0&&<div className="rounded-3xl border border-dashed border-zinc-300 bg-white p-10 text-center text-xs font-bold text-zinc-500">No posts yet.</div>}</section></div></main>;
}
