"use client";
import { memo, useState } from "react";
import { Heart, MessageCircle, Sparkles, WalletCards } from "lucide-react";
import { SHOP_PRODUCTS, type ShopProduct } from "@/lib/shop";
import { UpiPaymentDialog } from "@/components/payments/upi-payment-dialog";

const LIKE_PRODUCTS: ShopProduct[] = ["extra_likes_5", "extra_likes_15", "extra_likes_30"];
const SUPERLIKE_PRODUCTS: ShopProduct[] = ["superlike_1", "superlike_5"];
const SUPERCHAT_PRODUCTS: ShopProduct[] = ["superchat_credit_1", "superchat_credit_3"];
function ProductIcon({ product }: { product: ShopProduct }) { if (product.startsWith("superchat")) return <MessageCircle className="h-4 w-4"/>; if (product.startsWith("superlike")) return <Sparkles className="h-4 w-4"/>; return <Heart className="h-4 w-4 fill-current"/>; }
function Section({ title, eyebrow, description, icon, products, onBuy }: { title:string; eyebrow:string; description:string; icon:React.ReactNode; products:ShopProduct[]; onBuy:(p:ShopProduct)=>void }) { return <section className="scroll-mt-20 space-y-2.5"><div className="flex items-center gap-2 px-0.5"><div className="flex h-7 w-7 shrink-0 items-center justify-center rounded-lg bg-muted text-foreground">{icon}</div><div><p className="text-[8px] font-black uppercase tracking-[.14em] text-[#761f30]">{eyebrow}</p><h2 className="text-base font-black tracking-tight text-foreground">{title}</h2><p className="text-[9px] leading-3.5 text-muted-foreground">{description}</p></div></div><div className="grid gap-2">{products.map((product,index)=>{const config=SHOP_PRODUCTS[product];return <article key={product} className={`relative flex min-h-[104px] flex-col rounded-2xl border bg-card p-3 shadow-sm ${index===products.length-1&&products.length>1?"border-[#e5cbd0] ring-1 ring-[#faf0f2]":"border-border"}`}><div className="flex items-start gap-2.5 pr-16"><div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-xl bg-muted text-foreground"><ProductIcon product={product}/></div><div className="min-w-0"><h3 className="text-xs font-black leading-4 text-foreground">{config.label}</h3><p className="mt-0.5 text-[9px] leading-3.5 text-muted-foreground">{config.description}</p></div></div><div className="mt-auto flex items-end justify-between gap-2 pt-2.5"><div><span className="text-xl font-black tracking-tight text-foreground">₹{config.amountPaise/100}</span><p className="text-[8px] font-medium text-muted-foreground">one-time</p></div><button type="button" onClick={()=>onBuy(product)} className="flex min-h-9 shrink-0 items-center justify-center rounded-lg bg-zinc-950 px-3 text-[9px] font-black text-white">Buy with UPI</button></div></article>})}</div></section> }
export const DateBuShop = memo(function ExtrovertShop() {
  const [product,setProduct]=useState<ShopProduct|null>(null);
  const config=product?SHOP_PRODUCTS[product]:null;
  return <div className="space-y-6"><Section eyebrow="One-time · Likes" title="Extra Likes" description="More chances to say yes today." icon={<Heart className="h-3.5 w-3.5"/>} products={LIKE_PRODUCTS} onBuy={setProduct}/><Section eyebrow="One-time · Super Likes" title="Super Likes" description="Make one profile stand out." icon={<Sparkles className="h-3.5 w-3.5"/>} products={SUPERLIKE_PRODUCTS} onBuy={setProduct}/><Section eyebrow="One-time · SuperChats" title="SuperChats" description="Send a direct message before a match." icon={<MessageCircle className="h-3.5 w-3.5"/>} products={SUPERCHAT_PRODUCTS} onBuy={setProduct}/><div className="flex items-center justify-center gap-1.5 border-t border-border pt-4 text-[8px] font-semibold text-muted-foreground"><WalletCards className="h-3 w-3 text-[#761f30]"/> Direct UPI checkout · transaction verified before delivery</div>{product&&config&&<UpiPaymentDialog endpoint="/api/upi/create-order" body={{product}} amountPaise={config.amountPaise} title={config.label} description="Pay directly from your UPI app. Your purchase is delivered after the transaction is verified." onClose={()=>setProduct(null)} onSubmitted={()=>setProduct(null)}/>}</div>;
});
DateBuShop.displayName="ExtrovertShop";
