"use client";

import { useEffect, useState } from "react";
import { MessageCircle, WalletCards, X } from "lucide-react";
import { SHOP_PRODUCTS } from "@/lib/shop";
import { createClient } from "@/lib/supabase/client";
import { UpiPaymentDialog } from "@/components/payments/upi-payment-dialog";

type Props = { targetUserId: string; targetName: string; onClose: () => void; onComplete?: () => void };
type WalletClient = { from: (table: string) => { select: (columns: string) => { maybeSingle: () => Promise<{ data: { purchased_superchats?: number } | null }> } }; rpc: (name: string, args: Record<string, string>) => Promise<{ error: { message: string } | null }> };

export default function SuperChatComposer({ targetUserId, targetName, onClose, onComplete }: Props) {
  const [content,setContent]=useState(""); const [loading,setLoading]=useState(false); const [error,setError]=useState<string|null>(null); const [credits,setCredits]=useState(0); const [paying,setPaying]=useState(false); const product=SHOP_PRODUCTS.superchat;
  useEffect(()=>{const supabase=createClient() as unknown as WalletClient; void supabase.from("superchat_wallets").select("purchased_superchats").maybeSingle().then(({data})=>setCredits(data?.purchased_superchats??0));},[]);
  async function sendWithCredit(){const text=content.trim();if(!text||loading)return;try{setLoading(true);setError(null);const supabase=createClient() as unknown as WalletClient;const {error:rpcError}=await supabase.rpc("send_superchat_with_credit",{p_recipient_id:targetUserId,p_content:text});if(rpcError)throw new Error(rpcError.message.includes("SUPERCHAT_EMPTY")?"Your SuperChat credits are empty.":"Couldn't send the SuperChat. Please try again.");setCredits(v=>Math.max(0,v-1));onComplete?.();onClose();}catch(err){setError(err instanceof Error?err.message:"Unable to send SuperChat.");}finally{setLoading(false);}}
  return <div className="fixed inset-0 z-[10003] flex items-center justify-center bg-black/60 p-3 backdrop-blur-md"><div className="max-h-[calc(100dvh-2rem)] w-full max-w-md overflow-y-auto rounded-[2rem] border border-zinc-200 bg-white p-5 text-zinc-950 shadow-[0_24px_80px_rgba(0,0,0,.24)] sm:p-6"><div className="flex items-start justify-between gap-3"><div><div className="inline-flex items-center gap-1.5 rounded-full bg-violet-50 px-2.5 py-1 text-[10px] font-black uppercase tracking-[0.14em] text-violet-700"><MessageCircle className="h-3.5 w-3.5"/>SuperChat</div><h2 className="mt-2 text-xl font-black">Message {targetName}</h2><p className="mt-1.5 text-xs leading-5 text-zinc-600">Send one direct message before matching.</p></div><button type="button" onClick={onClose} className="grid h-9 w-9 place-items-center rounded-full border border-zinc-200 bg-zinc-50" aria-label="Close"><X className="h-4 w-4"/></button></div><div className="mt-5 rounded-2xl border border-violet-200 bg-violet-50/40 p-3.5"><textarea value={content} onChange={e=>setContent(e.target.value.slice(0,500))} rows={5} autoFocus placeholder="Say something genuine..." className="min-h-[120px] w-full resize-none rounded-xl border border-zinc-200 bg-white px-3.5 py-3 text-sm outline-none focus:border-violet-500"/><div className="mt-2 flex items-center justify-between text-[9px] font-semibold text-zinc-500"><span>{content.length}/500</span><span>Be respectful.</span></div></div>{error&&<p role="alert" className="mt-3 rounded-2xl border border-rose-200 bg-rose-50 px-3 py-2.5 text-[10px] font-bold text-rose-700">{error}</p>}<button type="button" onClick={()=>credits>0?void sendWithCredit():setPaying(true)} disabled={!content.trim()||loading} className="mt-4 flex w-full items-center justify-center gap-2 rounded-2xl bg-violet-600 py-3.5 text-xs font-black text-white disabled:opacity-45">{credits>0?<><WalletCards className="h-4 w-4"/>Use SuperChat credit · {credits} left</>:<>Send SuperChat · ₹{product.amountPaise/100}</>}</button><p className="mt-3 text-center text-[9px] font-semibold text-zinc-400">{credits>0?"Using your purchased credit":"Pay directly with UPI; delivery follows transaction verification."}</p>{paying&&<UpiPaymentDialog endpoint="/api/upi/create-order" body={{product:"superchat",targetUserId,content:content.trim()}} amountPaise={product.amountPaise} title={`SuperChat to ${targetName}`} description="Pay directly from UPI. The SuperChat is sent after the transaction is verified." onClose={()=>setPaying(false)} onSubmitted={()=>{setPaying(false);onComplete?.();onClose();}}/>}</div></div>;
}
