import type { Metadata } from "next";
import Link from "next/link";
import Image from "next/image";
import { redirect } from "next/navigation";
import { MapPin, ShieldCheck, Star, GraduationCap, Briefcase, UserRound, CalendarDays } from "lucide-react";
import { createServerSupabaseClient } from "@/lib/supabase/server";
import { routes } from "@/config/routes";
import { getProfilePhotoUrl } from "@/lib/profile-photo";
import { calculateAge } from "@/lib/utils";

export const metadata: Metadata = { title: "Profile | Extrovert" };
export const dynamic = "force-dynamic";

type ProfileInterest = { id: string; name: string };
type ProfileInterestRow = { interests?: ProfileInterest | ProfileInterest[] | null };
function clean(value: string | null | undefined, fallback = "Not added") { return value?.trim() || fallback; }
function prettyType(value: string | null | undefined) { const v=(value??"").trim().toLowerCase(); if(v==="student")return "Student"; if(v==="professional")return "Professional"; if(v==="other")return "Other"; return clean(value,"Not set").replace(/[-_]+/g," ").replace(/\b\w/g,c=>c.toUpperCase()); }
function prettyGender(value: string | null | undefined) { const v=(value??"").trim().toLowerCase(); if(v==="man")return "Man"; if(v==="woman")return "Woman"; if(v==="non-binary"||v==="nonbinary")return "Non-binary"; return clean(value,"Not set").replace(/[-_]+/g," ").replace(/\b\w/g,c=>c.toUpperCase()); }
function prettyYear(value: string | null | undefined) { if(!value)return "Not added"; const map:Record<string,string>={"1st-year":"1st year","2nd-year":"2nd year","3rd-year":"3rd year","4th-year":"4th year","5th-year":"5th year",postgraduate:"Postgraduate"}; return map[value]??value.replace(/[-_]+/g," ").replace(/\b\w/g,c=>c.toUpperCase()); }
function TrustBadge({ok,yes,no}:{ok:boolean;yes:string;no:string}){return <span className={`inline-flex items-center gap-1 rounded-full border px-2 py-1 text-[9px] font-black ${ok?"border-emerald-200 bg-emerald-50 text-emerald-700":"border-rose-200 bg-rose-50 text-rose-700"}`}><ShieldCheck className="h-2.5 w-2.5"/>{ok?yes:no}</span>}
function Info({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div className="rounded-2xl border border-zinc-200 bg-zinc-50/70 p-3"><div className="flex items-center gap-1.5 text-[9px] font-black uppercase tracking-wider text-zinc-500">{icon}{label}</div><p className="mt-1.5 break-words text-xs font-black text-zinc-900">{value}</p></div>}

export default async function ProfilePage(){
 const supabase=await createServerSupabaseClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user)redirect(routes.login);
 const [{data:profile},{data:preferences},{data:identity}]=await Promise.all([
  supabase.from("profiles").select("id,bio,profile_completed,ghost_mode,campus_residency,campus_hangout,relationship_goal,zodiac,sleep_habit,caffeine_pref,weekend_vibe,prompt_question,prompt_answer,profile_photos(id,storage_path,is_primary,display_order),profile_interests(interests(id,name))").eq("id",user.id).maybeSingle(),
  supabase.from("dating_preferences").select("interested_in,min_age,max_age,preferred_department").eq("user_id",user.id).maybeSingle(),
  supabase.from("extrovert_profiles").select("id,display_name,date_of_birth,gender,identity_type,institution_name,field_of_study,department,academic_year,job_title,employer_name,role_description,verification_status,area_verification_status,area_id,profile_photo_path").eq("id",user.id).maybeSingle()
 ]);
 if(!profile?.profile_completed||!identity)redirect(routes.profileSetup);
 const photos=[...(profile.profile_photos??[])].sort((a,b)=>a.display_order-b.display_order); const photoUrls=photos.map(p=>getProfilePhotoUrl(p.storage_path,480)).filter(Boolean) as string[]; const sharedPhoto=getProfilePhotoUrl(identity.profile_photo_path,480); const primaryPhoto=photoUrls[0]??sharedPhoto;
 const age=identity.date_of_birth?calculateAge(identity.date_of_birth):null; const interestRows=(profile.profile_interests??[]) as ProfileInterestRow[]; const interests=interestRows.flatMap(pi=>pi.interests?(Array.isArray(pi.interests)?pi.interests:[pi.interests]):[]);
 const areaResult=identity.area_id?await supabase.from("extrovert_areas").select("name").eq("id",identity.area_id).maybeSingle():null; const areaName=areaResult?.data?.name??"Not added";
 const type=(identity.identity_type??"").trim().toLowerCase(); const isStudent=type==="student"; const isProfessional=type==="professional";
 return <main className="mx-auto max-w-md space-y-3.5 px-3.5 pb-24 pt-3 font-sans text-zinc-950 md:pt-4">
  <div className="px-1"><p className="text-[10px] font-black uppercase tracking-[.16em] text-emerald-600">YOU</p><h1 className="text-2xl font-black tracking-tight">Your profile</h1></div>
  <section className="overflow-hidden rounded-[2rem] border border-zinc-200 bg-white shadow-sm"><div className="relative aspect-[4/5] max-h-[520px] w-full bg-zinc-100">{primaryPhoto?<Image src={primaryPhoto} alt={identity.display_name??"Profile"} fill priority decoding="async" className="object-cover" sizes="(max-width:640px) 100vw,448px"/>:<div className="flex h-full items-center justify-center bg-emerald-50 text-6xl font-black text-emerald-300">{identity.display_name?.charAt(0)??"?"}</div>}<div className="absolute right-3 top-3 flex max-w-[80%] flex-col items-end gap-1.5"><TrustBadge ok={identity.verification_status==="verified"} yes="Identity verified" no="Identity not verified"/><TrustBadge ok={identity.area_verification_status==="verified"} yes="Area verified" no="Area not verified"/></div><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/75 via-black/15 to-transparent p-5 pt-20 text-white"><div className="flex flex-wrap items-baseline gap-1.5"><h2 className="text-3xl font-black">{clean(identity.display_name,"Member")}</h2>{age!==null&&<span className="text-xl font-medium text-white/80">{age}</span>}</div><p className="mt-1 text-xs font-semibold text-white/85">{prettyType(identity.identity_type)}</p><p className="mt-1 flex items-center gap-1 text-[10px] text-white/75"><MapPin className="h-3 w-3"/>{areaName}</p></div></div><div className="p-4">{profile.bio?<p className="text-sm leading-6 text-zinc-700">“{profile.bio}”</p>:<p className="text-xs text-zinc-400">No bio added yet.</p>}</div></section>
  <section className="rounded-3xl border border-zinc-200 bg-white p-4 shadow-sm"><div className="mb-3 flex items-start gap-3"><div className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-emerald-50 text-emerald-700"><UserRound className="h-4 w-4"/></div><div><h2 className="text-sm font-black">Who are you?</h2><p className="mt-1 text-[10px] leading-4 text-zinc-500">Identity details are managed in Profile setup. Officially verified name, gender and age are locked.</p></div></div><div className="grid grid-cols-2 gap-2"><Info icon={<UserRound className="h-3 w-3"/>} label="Name" value={clean(identity.display_name)}/><Info icon={<ShieldCheck className="h-3 w-3"/>} label="Gender" value={prettyGender(identity.gender)}/><Info icon={<CalendarDays className="h-3 w-3"/>} label="Age" value={age!==null?String(age):"Not available"}/><Info icon={<MapPin className="h-3 w-3"/>} label="Area" value={areaName}/></div></section>
  <section className="rounded-3xl border border-zinc-200 bg-white p-4 shadow-sm"><div className="mb-3 flex items-start gap-3"><div className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-emerald-50 text-emerald-700">{isStudent?<GraduationCap className="h-4 w-4"/>:<Briefcase className="h-4 w-4"/>}</div><div><h2 className="text-sm font-black">{isStudent?"Student context":isProfessional?"Work context":"Current context"}</h2><p className="mt-1 text-[10px] leading-4 text-zinc-500">The study or work information people see on your dating profile.</p></div></div>{isStudent?<div className="grid grid-cols-2 gap-2"><Info icon={<GraduationCap className="h-3 w-3"/>} label="College / university" value={clean(identity.institution_name)}/><Info icon={<Briefcase className="h-3 w-3"/>} label="Course / department" value={clean(identity.department)}/><Info icon={<GraduationCap className="h-3 w-3"/>} label="Field of study" value={clean(identity.field_of_study)}/><Info icon={<CalendarDays className="h-3 w-3"/>} label="Academic year" value={prettyYear(identity.academic_year)}/></div>:isProfessional?<div className="grid grid-cols-2 gap-2"><Info icon={<Briefcase className="h-3 w-3"/>} label="Job / role" value={clean(identity.job_title)}/><Info icon={<Briefcase className="h-3 w-3"/>} label="Company / organisation" value={clean(identity.employer_name)}/><div className="col-span-2"><Info icon={<UserRound className="h-3 w-3"/>} label="About the role" value={clean(identity.role_description)}/></div></div>:<Info icon={<UserRound className="h-3 w-3"/>} label="What you do" value={clean(identity.role_description)}/>}</section>
  {photoUrls.length>0&&<section className="rounded-[1.75rem] border border-zinc-200 bg-white p-3.5"><div className="mb-2"><span className="text-[10px] font-black uppercase tracking-wider text-zinc-500">Dating photos · {photoUrls.length}/6</span></div><div className="grid grid-cols-3 gap-2">{photoUrls.map((url,i)=><div key={i} className="relative aspect-[4/5] overflow-hidden rounded-2xl bg-zinc-100"><Image src={url} alt={`Dating photo ${i+1}`} fill decoding="async" className="object-cover" sizes="(max-width:640px) 30vw,140px"/>{i===0&&<span className="absolute left-1 top-1 rounded-full bg-white/90 px-1.5 py-0.5 text-[8px] font-bold text-zinc-700"><Star className="mr-0.5 inline h-2 w-2 fill-current text-emerald-600"/>Main</span>}</div>)}</div></section>}
  <section className="rounded-2xl border border-zinc-200 bg-white p-4"><span className="text-[10px] font-black uppercase tracking-wider text-zinc-500">Dating vibe</span><div className="mt-2 flex flex-wrap gap-1.5">{[profile.relationship_goal,profile.zodiac,profile.sleep_habit,profile.caffeine_pref,profile.weekend_vibe].filter(Boolean).map(x=><span key={x} className="rounded-full bg-zinc-100 px-2.5 py-1 text-[11px] font-bold text-zinc-700">{x}</span>)}{![profile.relationship_goal,profile.zodiac,profile.sleep_habit,profile.caffeine_pref,profile.weekend_vibe].some(Boolean)&&<span className="text-xs text-zinc-400">Nothing added yet.</span>}</div></section>
  <section className="rounded-2xl border border-zinc-200 bg-white p-4"><span className="text-[10px] font-black uppercase tracking-wider text-zinc-500">Interests</span><div className="mt-2 flex flex-wrap gap-1.5">{interests.length?interests.map(i=><span key={i.id} className="rounded-full bg-emerald-50 px-2.5 py-1 text-[11px] font-bold text-emerald-800">{i.name}</span>):<span className="text-xs text-zinc-400">No interests added yet.</span>}</div></section>
  <section className="rounded-2xl border border-emerald-100 bg-emerald-50/60 p-4"><span className="text-[10px] font-black uppercase tracking-wider text-emerald-700">Prompt</span>{profile.prompt_question&&profile.prompt_answer?<><p className="mt-1 text-sm font-bold">{profile.prompt_question}</p><p className="mt-1 text-sm text-zinc-700">“{profile.prompt_answer}”</p></>:<p className="mt-2 text-xs text-zinc-500">Add a prompt to make starting a conversation easier.</p>}</section>
  <section className="rounded-2xl border border-zinc-200 bg-white p-4"><span className="text-[10px] font-black uppercase tracking-wider text-zinc-500">Discovery preferences</span><div className="mt-2 flex flex-wrap gap-1.5"><span className="rounded-full bg-zinc-100 px-2.5 py-1 text-[11px] font-bold text-zinc-700">{preferences?.interested_in?.includes("everyone")?"Everyone":prettyGender(preferences?.interested_in?.[0])}</span><span className="rounded-full bg-zinc-100 px-2.5 py-1 text-[11px] font-bold text-zinc-700">{preferences?.min_age ?? 18}–{preferences?.max_age ?? 30}</span></div></section>
 </main>
}
